---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00_amd-device-plugin-config.yaml
  - 01_sriov-amd-vnic-policy.yaml
  - 02_sriov-amd-vnic-net.yaml
  - 03_sriov-nic-test.yaml
